### PR TITLE
Upgrade samples for lagom 1.5.0

### PR DESCRIPTION
**Pull request by ignasi35**
related to https://github.com/playframework/play-meta/issues/13

### CODE REVIEW

**Comment by TimMoore** [comment]
Should the 1.5 update remove the health check routes registration?

https://github.com/lagom/shopping-cart-scala/blob/0f44f6089fa65a7c2c68ec5b3b7913ef002ad001/shopping-cart-impl/src/main/resources/prod-application.conf#L43

I think that's redundant with https://github.com/lagom/lagom/pull/1738 and may even cause an error.

**Comment by ignasi35** [comment]
@TimMoore yeah, that setting must go and also a few other details (like explicit dependencies to bootstrap, etc...)

**Comment by TimMoore** [comment]
Will you raise a new issue or should I?

**Comment by TimMoore** [comment]
This might also be good material for the migration guide.

**Comment by ignasi35** [comment]
> This might also be good material for the migration guide.

Definitely. Unfortunately some changes required in this repo are motivated by this repo using manual deployment (not LBO) on Lagom 1.4.11.

**Pull request merged**
